apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: book-service

resources:
  - ../../base

images:
  - name: registry.yourdomain.com/book-service
    newTag: dev

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: book-service
        namespace: book-service
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: book-service
                resources:
                  requests:
                    cpu:    "50m"
                    memory: "64Mi"
                  limits:
                    cpu:    "200m"
                    memory: "256Mi"
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: book-service-hpa
        namespace: book-service
      spec:
        minReplicas: 1
        maxReplicas: 3

configMapGenerator:
  - name: book-service-config
    namespace: book-service
    behavior: merge
    literals:
      - NODE_ENV=development
      - SERVICE_VERSION=dev