# Secret for Book Microservice

apiVersion: v1
kind: Secret
metadata:
  name: book-service-secret
  namespace: book-service
  labels:
    app.kubernetes.io/name:      book-microservice
    app.kubernetes.io/component: secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOjFxOEdDbFcybkFCbUBib29rLXBvc3RncmVzLWhlYWRsZXNzLmJvb2stcG9zdGdyZXMuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9ib29rX2Ri
  JWT_SECRET: Y2VmOTA2YWEyZThhZDA4ZDliN2U1NGQwZmU3NWU5OTY3MDc5MjU1ZDAzNzI0MWIwMTJjODVjMTYyZDBlMTJmZjljYWQwNWQwZDc5OGY0ZjQ2MzdlNjU1NWE5NDYwNGYxMzQyYWQwNjNhMzcwODg3ZDIwYzhmMzc0ZWMyMGJiNGI=
  S3_ACCESS_KEY: bWluaW9hZG1pbg==
  S3_SECRET_KEY: bWluaW9hZG1pbg==
  INTERNAL_SERVICE_SECRET: ZDk5ZDA2YWRkZDNmMGNiNTJhMTEzOGExNzMyN2IzZGQxY2M3M2M3YWY2MDRkNjBlZWIxOTM4MzM2MzliY2Ri